name: 'Terragrunt_CD'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:   
  Terragrunt:     
    name: 'Terragrunt'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
        working-directory: "./non-prod"
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Azure Login using OIDC
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terragrunt Init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_USE_MSI: true
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terragrunt init --terragrunt-non-interactive
      
    - name: Terragrunt Validate
      run: terragrunt validate
      
    - name: Tflint  init
      run: tflint --init
      
    - name: Run Tflint
      run: tflint -f compact

    - name: Terragrunt Plan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_USE_MSI: true
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terragrunt run-all plan # --terragrunt-non-interactive

    - name: Terragrunt Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_USE_MSI: true
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true 
      run: terragrunt run-all apply --terragrunt-non-interactive
      
    - name: Terragrunt Output
      run: terragrunt output-all
      
#     - name: Terragrunt destroy
#       env:
#         ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#         ARM_USE_MSI: true
#         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#         ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#         ARM_USE_OIDC: true
#       run: terragrunt run-all destroy --terragrunt-non-interactive
