name: 'Terragrunt_CD'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:   
  Terragrunt:     
    name: 'Terragrunt'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: "./non-prod"
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Azure Login using OIDC
      uses: Azure/login@v2.2.0
      with:
        client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
          azcliversion: latest
          inlineScript: |
            az account show
    - name: Install Terragrunt
      run: |
        curl -fsSL https://github.com/gruntwork-io/terragrunt/releases/download/v0.44.1/terragrunt_linux_amd64 -o terragrunt
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/

    - name: Terragrunt Init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_USE_MSI: true
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terragrunt init --terragrunt-non-interactive
      
    - name: Terragrunt Validate
      run: terragrunt validate
    # - name: Install Tflint  # New Tflint installation step
    #   run: |
    #       go install github.com/terraform-linters/tflint@latest
    #       export PATH=$PATH:/usr/bin/bash
    - uses: terraform-linters/setup-tflint@v4
      with:
          tflint_version: v0.52.0  # Adjust version as needed
      
    - name: Tflint  init
      run: tflint --init
      
    - name: Run Tflint
      run: tflint -f compact

    - name: Terragrunt Plan
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_USE_MSI: true
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true
      run: terragrunt run-all plan # --terragrunt-non-interactive

    - name: Terragrunt Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_USE_MSI: true
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        ARM_USE_OIDC: true 
      run: terragrunt run-all apply --terragrunt-non-interactive
      
    - name: Terragrunt Output
      run: terragrunt output-all
      
#     - name: Terragrunt destroy
#       env:
#         ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#         ARM_USE_MSI: true
#         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#         ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#         ARM_USE_OIDC: true
#       run: terragrunt run-all destroy --terragrunt-non-interactive
